config/routes.rb
Cookery::Application.routes.draw do
  resources :categories

  resources :dishes

  root :to => "categories#home"

  match '/recipe', :to => "dishes#recipe"

  match '/sort', :to => "dishes#sort"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :dishes

	validates :name, :presence => true,
					 :uniqueness => true

	scope :presents, where(:deleted => false)

	def del_depends_dishes
	  self.dishes.each do |d|
	   d.deleted = true
	   d.save!
      end
    end

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :category

	scope :presents, where(:deleted => false)

	validates_presence_of :name, :recipe
	validates :recipe, :length => { :maximum => 1000}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def home
  	@categories = Category.presents
  	#@dishes = Dishes.presents
  end
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.presents

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(categories_path, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => categories_path }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(categories_path, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.deleted = true
    @category.del_depends_dishes
    @category.save!

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.xml
  def index
    @dishes = Dish.presents

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dishes }
    end
  end

  def sort
  	@dishes = Dish.presents.order(:name)

  	respond_to do |format|
  		format.js
  	end
  end

  def recipe
  	@dish = Dish.find(params[:id])

   #render 'recipe'
  end

  # GET /dishes/1
  # GET /dishes/1.xml
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.xml
  def new
    @dish = Dish.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
  	@categories = Category.all
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.xml
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to(dishes_path, :notice => 'Dish was successfully created.') }
        format.xml  { render :xml => @dish, :status => :created, :location => dishes_path }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.xml
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to(dishes_path, :notice => 'Dish was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.xml
  def destroy
    @dish = Dish.find(params[:id])
    @dish.deleted = true
    @dish.save!
    @dishes = Dish.presents

    respond_to do |format|
      format.html { redirect_to(dishes_url) }
      format.xml  { head :ok }
      format.js 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Создать" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Изменеие категории</h1>

<%= render 'form' %>

<h3><%= link_to 'Назад', categories_path %></h3>

app/views/categories/home.html.erb
<h1>Кулинарная книга</h1>

<table>
  <tr>
    <th></th>
    <th></th>
  </tr>

 <%= image_tag("blyudo1.jpg")%>


</table>

<br />
<h3>
<%= link_to 'Добавить новую категорию блюд   ', new_category_path %>|
<%= link_to '   Создать новое блюдо', new_dish_path %>
</h3>

app/views/categories/index.html.erb
<h1>Категории блюд</h1>

<table>

<% @categories.each do |category| %>
  <tr>
    <td><h3><%= link_to "#{category.name}  ", category %></h3></td>
    <td><h3><%= link_to "   блюдо в эту категорию", new_dish_path(:id => category)%></h3></td>
<% end %>
</table>

<br />

<h3><%= link_to 'Создать новую категорию блюд', new_category_path %></h3>

app/views/categories/new.html.erb
<h1>Новая категория</h1>

<%= render 'form' %>

<h3><%= link_to 'Назад', categories_path %></h3>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @category.name %></h1> <h3><%= link_to 'Править', edit_category_path(@category) %> |
   <%= link_to 'Назад', categories_path %> | <%= link_to 'Удалить', @category, :confirm => 'Вы уверены? Все блюда, находящиеся в этой категории будут удалены', :method => :delete %></h3>
</p>

<p>
  <% if !@category.dishes.empty? %>
   <h2> Блюда:</h2>
   <table>
  <tr>
    <th></th>
    <th></th>
  </tr>
  
    <% @category.dishes.presents.each do |dish| %>
    <tr>
    
     <td><h3> <%=dish.name %></h3>  </td> 
     <td><h3>  <%= link_to "Рецепт", recipe_path(:id => dish)%></h3></td>
    <% end %>
  <% else %>
    <h3> В этой категории пока нет блюд </h3>
  <%end%>
</p>

<h3><%= link_to 'Создать новую категорию блюд', new_category_path %></h3>

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Рецепт проготовления" %><br />
    <%= f.text_area :recipe, id:'txt', onkeypress: 'return CheckLength()';%>
    <p>Осталось <span id="info">1000</span> символов.</p>
  </div>
  <div class="field">
    <%= f.label "Категория" %><br />
  <%=  select("dish", "category_id", Category.presents.all.collect {|c| [ c.name, c.id ] }, {:disabled => 'restricted'}, {:include_blank => false})%>

  </div>
  <%= javascript_tag do %>setInterval(CheckLength, 1000)<% end %> 
  <div class="actions">
    <%= f.submit "Создать"%>
  </div>
<% end %>

app/views/dishes/_index.html.erb
  <tr>
    <th><%= link_to "Название", sort_path, :remote => true%></th>

  </tr>

<% @dishes.each do |dish| %>

  <tr>
    <td><h3><%= link_to "#{dish.name}", dish %></h3></td>
    <td><h3><%= link_to "Удалить", dish, :method => :delete, :confirm => "Are you sure?", :remote => true %></h3></td>
    <td><h3><%= dish.category.name %></h3></td>
    <td><h3><%= link_to "рецепт", recipe_path(:id => dish)%></h3></td>
  </tr>

<% end %>

app/views/dishes/destroy.js.erb
$("dish_list").update("<%= escape_javascript (render('index')) %>")

app/views/dishes/edit.html.erb
<h1>Изменнение блюда</h1>

<%= render 'form' %>

<%= link_to 'Назад', dishes_path %>

app/views/dishes/index.html.erb
<h1>Блюда</h1>
<% if @dishes.empty? %>
 <h3>Пока нет блюд</h3>
<% else %>
<table id = "dish_list">


<%= render :partial => 'index'%>

</table>
 
<br />
<% end %>
<h3><%= link_to 'Добавить новое блюдо', new_dish_path %></h3>

app/views/dishes/new.html.erb
<h1>Новое блюдо</h1>
<% if Category.presents.empty? %>
 <h2> Сначала созайте категорию <h2>
<% else %>
 <%= render 'form' %>
<% end %>

<h3><%= link_to 'Назад', dishes_path %></h3>

app/views/dishes/recipe.html.erb
<h2><%= word_wrap(@dish.recipe, :line_width => 52 ) %></h2>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p><h3>
  <b>Название:</b>
  <%= @dish.name %>
</h3></p>

<p><h3>
  <b>В категории:</b>
  <%= @dish.category.name%>
</h3></p>

<p><h3>
   <b> Рецепт:</b>
   <span class="content"><%= word_wrap(@dish.recipe, :line_width => 52) %></span>
</h3></p>

<h3><%= link_to 'Редактировать', edit_dish_path(@dish) %> |
<%= link_to 'Назад ', dishes_path %>|
<%= link_to 'Удалить', @dish, :confirm => 'Are you sure?', :method => :delete %></h3>

app/views/dishes/sort.js.erb
$("dish_list").update("<%= escape_javascript (render('index')) %>")

app/views/layouts/_header.html.erb
<header>
      <b><%= link_to "На главную", root_path %></b>&nbsp&nbsp&nbsp&nbsp&nbsp
      <b><%= link_to "Категории", categories_path %></b>&nbsp&nbsp&nbsp&nbsp&nbsp
      <b><%= link_to "Блюда", dishes_path %></b>
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookery</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div class="container">
  <%= render 'layouts/header'%>
  

<%= yield %>

 </div>
</body>
</html>